// fetchArticles
export const FETCH_ARTICLES_REQUESTS = 'FETCH_ARTICLES_REQUESTS';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

// fetchArticlesByTopic
export const FETCH_ARTICLES_BY_TOPIC_REQUESTS = 'FETCH_ARTICLES_BY_TOPIC_REQUESTS';
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS = 'FETCH_ARTICLES_BY_TOPIC_SUCCESS';
export const FETCH_ARTICLES_BY_TOPIC_ERROR = 'FETCH_ARTICLES_BY_TOPIC_ERROR';

// fetchArticlesByID
export const FETCH_ARTICLES_BY_ID_REQUESTS = 'FETCH_ARTICLES_BY_ID_REQUESTS';
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ID_ERROR = 'FETCH_ARTICLES_BY_ID_ERROR';

// fetchArticlesByUser
export const FETCH_ARTICLES_BY_USER_REQUESTS = 'FETCH_ARTICLES_BY_USER_REQUESTS';
export const FETCH_ARTICLES_BY_USER_SUCCESS = 'FETCH_ARTICLES_BY_USER_SUCCESS';
export const FETCH_ARTICLES_BY_USER_ERROR = 'FETCH_ARTICLES_BY_USER_ERROR';

// fetchCommentsByArticleID
export const FETCH_COMMENTS_BY_ARTICLE_ID_REQUESTS = 'FETCH_COMMENTS_BY_ARTICLE_ID_REQUESTS';
export const FETCH_COMMENTS_BY_ARTICLE_ID_SUCCESS = 'FETCH_COMMENTS_BY_ARTICLE_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ARTICLE_ID_ERROR = 'FETCH_COMMENTS_BY_ARTICLE_ID_ERROR';

// fetchCommentsByUser
export const FETCH_COMMENTS_BY_USER_REQUESTS = 'FETCH_COMMENTS_BY_USER_REQUESTS';
export const FETCH_COMMENTS_BY_USER_SUCCESS = 'FETCH_COMMENTS_BY_USER_SUCCESS';
export const FETCH_COMMENTS_BY_USER_ERROR = 'FETCH_COMMENTS_BY_USER_ERROR';

// addCommentsByArticleID
export const ADD_COMMENTS_BY_ARTICLE_ID_POST = 'ADD_COMMENTS_BY_ARTICLE_ID_POST';
export const ADD_COMMENTS_BY_ARTICLE_ID_SUCCESS = 'ADD_COMMENTS_BY_ARTICLE_ID_SUCCESS';
export const ADD_COMMENTS_BY_ARTICLE_ID_ERROR = 'ADD_COMMENTS_BY_ARTICLE_ID_ERROR';

// fetchTopics
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

// articleVoteUp
export const ARTICLE_VOTE_UP_REQUEST = 'ARTICLE_VOTE_UP_REQUEST';
export const ARTICLE_VOTE_UP_SUCCESS = 'ARTICLE_VOTE_UP_SUCCESS';
export const ARTICLE_VOTE_UP_ERROR = 'ARTICLE_VOTE_UP_ERROR';

// articleVoteDown
export const ARTICLE_VOTE_DOWN_REQUEST = 'ARTICLE_VOTE_DOWN_REQUEST';
export const ARTICLE_VOTE_DOWN_SUCCESS = 'ARTICLE_VOTE_DOWN_SUCCESS';
export const ARTICLE_VOTE_DOWN_ERROR = 'ARTICLE_VOTE_DOWN_ERROR';

// fetchUser
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

// fetchAllUsers
export const FETCH_ALL_USERS_REQUESTS = 'FETCH_ALL_USERS_REQUESTS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_ERROR = 'FETCH_ALL_USERS_ERROR';

// fetchUserByUsername
export const FETCH_USER_BY_USERNAME_REQUESTS = 'FETCH_USER_BY_USERNAME_REQUESTS';
export const FETCH_USER_BY_USERNAME_SUCCESS = 'FETCH_USER_BY_USERNAME_SUCCESS';
export const FETCH_USER_BY_USERNAME_ERROR = 'FETCH_USER_BY_USERNAME_ERROR';
